### ISSUE TITLE
Domain Lecture entities

### ISSUE THREAD

**Issue by ESPOIR-DITE** [ESPOIR-DITE/kelasi_api#1]
all the classes in Lecture directory.

**Comment by TaylorLok** [comment]
Received

**Comment by ESPOIR-DITE** [comment]
Thanks TaylorLok. Don't worry about RoleOfLecture, I have taken care of it. so in your package you only have 4 classes now.
I am proceeding into closing this issue.
from Monday you have a new task. 
Enjoy the rest of the day brother.
